import Card from "@/components/Card";
import DashboardLayout from "@/layouts/DashboardLayout";

const SmartFloodDetection = () => {
  return (
    <DashboardLayout>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
      <Card>
        <h1>Hello</h1>
      </Card>
    </DashboardLayout>
  );
};

export default SmartFloodDetection;
